<?php

namespace GoDaddy\Support;

enum ErrorCode: int
{
    // Common HTTP errors
    case UNAUTHORIZED = 401;
    case FORBIDDEN = 403;
    case NOT_FOUND = 404;
    case VALIDATION_FAILED = 422;
    case INTERNAL_ERROR = 500;

    // Abuse Service
    case ABUSE_TICKET_FAILED = 1000;
    case ABUSE_TICKET_CREATION_FAILED = 1001;
    case ABUSE_TICKET_LIST_FAILED = 1002;
    case ABUSE_TICKET_RETRIEVE_FAILED = 1003;

    // Countries Service
    case COUNTRY_LIST_FETCH_FAILED = 1100;
    case COUNTRY_DETAILS_FETCH_FAILED = 1101;

    // Domains Service
    case DOMAIN_FAILED = 2000;
    case DOMAIN_SEARCH_FAILED = 2001;
    case DOMAIN_REGISTRATION_FAILED = 2002;
    case DOMAIN_UPDATE_FAILED = 2003;
    case DOMAIN_DELETE_FAILED = 2004;

    // Orders Service
    case ORDER_LIST_FETCH_FAILED = 3000;
    case ORDER_DETAILS_FETCH_FAILED = 3001;

    // Certificates Service
    case CERTIFICATE_FAILED = 4000;
    case CERTIFICATE_ISSUE_FAILED = 4001;
    case CERTIFICATE_REVOKE_FAILED = 4002;
    case CERTIFICATE_RETRIEVE_FAILED = 4003;
    case CERTIFICATE_REISSUE_FAILED = 4004;
    case CERTIFICATE_VALIDATION_FAILED = 4005;
    case CERTIFICATE_DETAILS_FETCH_FAILED = 4006;
    case CERTIFICATE_ACTIONS_FETCH_FAILED = 4007;
    case CERTIFICATE_EMAIL_RESEND_FAILED = 4008;
    case CERTIFICATE_ALTERNATE_EMAIL_FAILED = 4009;
    case CERTIFICATE_EMAIL_SPECIFIC_RESEND_FAILED = 4010;
    case CERTIFICATE_EMAIL_HISTORY_FETCH_FAILED = 4011;
    case CERTIFICATE_CALLBACK_UNREGISTER_FAILED = 4012;
    case CERTIFICATE_CALLBACK_FETCH_FAILED = 4013;
    case CERTIFICATE_CALLBACK_REGISTER_FAILED = 4014;
    case CERTIFICATE_CANCEL_FAILED = 4015;
    case CERTIFICATE_DOWNLOAD_FAILED = 4016;
    case CERTIFICATE_CREATION_FAILED = 4017;
    case CERTIFICATE_RENEW_FAILED = 4018;
    case CERTIFICATE_REVOKE_FAILED = 4019;
    case CERTIFICATE_SITE_SEAL_FETCH_FAILED = 4020;
    case CERTIFICATE_VERIFY_DOMAIN_FAILED = 4021;
    case CERTIFICATE_CUSTOMER_CERTIFICATES_FETCH_FAILED = 4022;
    case CERTIFICATE_CUSTOMER_CERTIFICATE_DETAILS_FETCH_FAILED = 4023;
    case CERTIFICATE_DOMAIN_VERIFICATION_STATUS_FETCH_FAILED = 4024;
    case CERTIFICATE_DOMAIN_VERIFICATION_DETAILS_FETCH_FAILED = 4025;
    case CERTIFICATE_ACME_EXTERNAL_ACCOUNT_BINDING_FETCH_FAILED = 4026;
    case CERTIFICATE_SEARCH_FAILED = 4027;
    case CERTIFICATE_DOWNLOAD_FAILED = 4028;

    // DNS Service
    case DNS_FAILED = 5000;
    case DNS_LIST_FAILED = 5001;
    case DNS_UPDATE_FAILED = 5002;
    case DNS_DELETE_FAILED = 5003;

    // Shoppers Service
    case SHOPPER_FAILED = 6000;
    case SHOPPER_FETCH_FAILED = 6001;
    case SHOPPER_CREATE_FAILED = 6002;
    case SHOPPER_UPDATE_FAILED = 6003;
    case SHOPPER_DELETE_FAILED = 6004;
    case SHOPPER_STATUS_FETCH_FAILED = 6005;
    case SHOPPER_PASSWORD_SET_FAILED = 6006;

    // Aftermarket Service
    case AFTERMARKET_FAILED = 7000;
    case AFTERMARKET_LISTINGS_FETCH_FAILED = 7001;
    case AFTERMARKET_LISTINGS_DELETE_FAILED = 7002;
    case AFTERMARKET_LISTINGS_CREATE_FAILED = 7003;

    // Agreements Service
    case AGREEMENTS_GET_FAILED = 8001;

    // Auctions Service
    case AUCTIONS_PLACE_BIDS_FAILED = 9001;

    // Parking Service
    case PARKING_FAILED = 10000;
    case PARKING_METRICS_FETCH_FAILED = 10001;
    case PARKING_METRICS_BY_DOMAIN_FETCH_FAILED = 10002;

    // Subscriptions Service
    case SUBSCRIPTION_FAILED = 11000;
    case SUBSCRIPTION_LIST_FETCH_FAILED = 11001;
    case SUBSCRIPTION_DETAIL_FETCH_FAILED = 11002;
    case SUBSCRIPTION_CANCEL_FAILED = 11003;
    case SUBSCRIPTION_UPDATE_FAILED = 11004;
    case SUBSCRIPTION_PRODUCT_GROUPS_FETCH_FAILED = 11005;

    // Fallback
    case UNKNOWN = 9999;
}
