<?php

namespace GoDaddy\Services\Domains\v2\Enums;

enum ActionType: string
{
    case DNSSEC_CREATE = 'DNSSEC_CREATE';
    case DNSSEC_DELETE = 'DNSSEC_DELETE';
    case DOMAIN_UPDATE_NAME_SERVERS = 'DOMAIN_UPDATE_NAME_SERVERS';
    case CHANGE_OF_REGISTRANT_DELETE = 'CHANGE_OF_REGISTRANT_DELETE';
    case DOMAIN_RENEW = 'DOMAIN_RENEW';
    case DOMAIN_TRANSFER_IN = 'DOMAIN_TRANSFER_IN';
    case DOMAIN_TRANSFER_OUT = 'DOMAIN_TRANSFER_OUT';
    case DOMAIN_REDEEM = 'DOMAIN_REDEEM';
} 